### ISSUE TITLE
prompts for password even though password is configured

### ISSUE THREAD

**Issue by neuronflow** [sorinipate/vpn-up-for-openconnect#8]
I have configured my password and judging from the output it seems to have worked, however later in the process it still prompts for the sudo pw, is there a way to disable this?

my config
```
SUDO=TRUE
    # TRUE          
    # FALSE         
SUDO_PASSWORD="Secret"
```

output:
```
$ vpn-up start
sudo -S
Running as root ...
Starting vpn-up.command ...
Process ID (PID) stored in /Users/meow/vpn-up.command.pid ...
Logs file (LOG) stored in /Users/meow/vpn-up.command.log ...
Which VPN do you want to connect to?
1) rawiss
2)
3) Quit
#? 1
Starting the rawiss on rawiss.med.tum.de using Cisco AnyConnect SSL VPN ...
Connecting without 2FA (NONE) ...
Connecting with certificate ...
Running the rawiss in background ...
Running the rawiss with detailed output ...
Password:
```

I also tried `SUDO=FALSE` without success.

I am running the newest OSX.

**Comment by sorinipate** [comment]
This should be addressed now. Details [here](https://github.com/sorinipate/vpn-up-for-openconnect/commit/f0cea9c60b2bf599b96679dcced82173b74d2b8f).
